clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: oe_content_extra

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/oe_content_extra
      - COMPOSERVER=--2
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sparql:
    # Temporarily fix the triple store version to avoid "Provisional data" terms.
    # @todo: Use the latest release once a solution for the "Provisional data" terms is implemented.
    image: registry.fpfis.eu/openeuropa/triple-store-dev:1.14.0
    pull: true
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba

pipeline:
  composer-install-highest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-update-lowest:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer update --prefer-lowest --prefer-stable --ansi --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - while ! mysqladmin ping -h mysql --silent; do sleep 1; done
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/phpunit --testdox

  debug:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.4
    - 8.0
